### ISSUE TITLE
在vue1中引入simditor-mention 无效

### ISSUE THREAD

**Issue by small-stone** [njleonzhang/vue-simditor#1]
非常感谢您的代码，我在Vue1中引入simditor可以正常使用，可是引入simditor-mention却无效，麻烦您指点一下，谢谢！
```js
import simditor from 'simditor';
import SimditorMention from 'simditor-mention'
```

**Comment by njleonzhang** [comment]
SimditorMention 我不清楚啊  你去那边`simditor-mention`的项目问一下吧
https://github.com/mycolorway/simditor-mention
